---
- name: "Check if Java is installed"
  shell: command -v java
  register: check_java
  failed_when: check_java.rc not in  (0, 1)
  changed_when: False
  tags:
    - kafka-install
    - java

- name: "Was Java installed?"
  debug: var=check_java

- name: "Install OpenJDK"
  apt: name=openjdk-7-jre-headless state=present
  sudo: yes
  when: check_java.rc != 0
  tags:
    - kafka-install
    - java
